# Generated by Django 3.0.3 on 2020-04-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200331_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='name',
            new_name='title',
        ),
    ]
