# Generated by Django 3.0.3 on 2020-04-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='articles',
            name='published',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
