# Generated by Django 3.0.3 on 2020-04-28 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0002_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
